### ISSUE TITLE
Mod Not Working

### ISSUE THREAD

**Issue by JeSuisLaPourToi** [IronLucario2012/MaskMakerNotchesMod#1]
I don't know if i made something wrong or if I don't look in the right place but the notches won't appear. 

I'm currently running on Scarab with Modding API 1.5.78.11833-71, ItemChanger 2.0.5+598 and the dependencies on a pre-existing save file. I didn't try to see if it works on a new save file.

I don't use a Randomizer because it seems to make my game crash on the start of a new save file (tried to launch a new classic save file with a Randomizer 4 build and MaskMakerNotches on but the game got stuck on main menu screen).

**Comment by IronLucario2012** [comment]
Having now tested to be sure, I can say that having the notches not appear on a save file which didn't have the mod installed when it was created is expected behaviour, as adding them to the world happens on save creation, not on save loading.

If the notches are still not there on a new save file, or if it's crashing like you said, can you attach a copy of your modlog.txt? It can usually be found in C:\Users\"USER"\AppData\LocalLow\Team Cherry\Hollow Knight\ModLog.txt where "USER" is your computer username-based folder.

**Comment by IronLucario2012** [comment]
Closing as it's been seven months with no reply.
