### ISSUE TITLE
The Mod Does Not Work

### ISSUE THREAD

**Issue by Flizilla** [IronLucario2012/MaskMakerNotchesMod#4]
the mod just kinda... doesn't work
at all
unless i'm missing something, there's no way i could find to actually buy notches from the mask maker, i've spent hours searching and looking trough the code but i don't seem to find anything useful. the mod also seems to only allow buying one notch, instead of the intended 6 in the code. if it's working fine, i'd appreciate a guide! thanks.

**Comment by Flizilla** [comment]
looking at the other issues, it seems like it's because the mod only works when making a new save
i'm thinking if somehow making a new save and copy-pasting the mod code into other save files could make it work?

**Comment by IronLucario2012** [comment]
Yeah, unfortunately it's not as simple as being able to add it to an existing save since - as mentioned in other issues - it adds the notches to the world on save creation. I'm afraid I don't know enough about how the saves are stored to be able to answer whether copy-pasting just this mod's added bits would help, but I suspect it's not as simple as that sounds that way either, unfortunately. Good luck looking at it if you do go that route, though.
