### ISSUE TITLE
Ubication

### ISSUE THREAD

**Issue by Darkblaider** [IronLucario2012/MaskMakerNotchesMod#5]
Hello, I can't find the specific location, could you show me an image or something to find it?
Thank you

**Comment by IronLucario2012** [comment]
They're in Mask Maker's room in Deepnest. Here's a labelled screenshot showing where it is in relation to the nearest stag stations.
![image](https://github.com/IronLucario2012/MaskMakerNotchesMod/assets/32879698/f3fc639d-60b4-4ac0-8a18-52822c6461d7)

If you're in that room but they're not showing up, it might be the case that you didn't have the mod active when starting that save, in which case I cannot help, unfortunately; it only works if it's on when the save is started originally because that's when it knows to add them.

Hope this helps?
